### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by Steenkuyl** [JimTheMan/Jims-Ngrx-Example#1]
Hello Jim the Man, you would definitely be the man if you can provide some good unit test examples for the ngrx part.

eg: how to test store.dispatch in the app.component. via jasmine spy?

**Comment by JimLynchCodes** [comment]
![download](https://cloud.githubusercontent.com/assets/5354163/20838698/b078eb50-b877-11e6-8223-6f072c81641f.png)

Hey Steenkuyl,

I haven't tried to do this yet. I vaguely remember reading admit how to do it in the docs, but I'll try to add tests this weekend. :)

Unit testing the @Effects should be interesting too!

**Comment by Steenkuyl** [comment]
Great, I am really struggling with this. I can't find any good up to date examples for ngrx angular 2 unit testing.

**Comment by JimLynchCodes** [comment]
Hey @Steenkuyl ,

I was playing around with this just now, and I'm wondering- do you really need to mock the store or prevent your components from dispatching to the store? I was able to add the store right into my app component's unit test like this: 
```
describe('AppComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent,
        SmartComponentComponent,
        DumbComponentComponent,
      ],
      imports: [
        StoreModule.provideStore({mainReducer}),

      ]
    });
  });
```

I'm not 100% sure that this is the right way to do it, but I would think that since the components are so dependent on the data from the store that trying to test each in isolation wouldn't really work (for example, without the state my component is throwing a ton of "variable is undefined" errors because it's expecting it's local vars to get data from the store.

If you really REALLY don't want it to dispatch events you may be able to use a mock store to define new functionality (or no functionality hehe) for the _dispatch_ method. Maybe like this:
```
beforeEach(() => addProviders([
    {provide: Store, useClass: MockStore}
  ]));
```

**Comment by Steenkuyl** [comment]
You only want to test if the actions are dispatched. You test the functionality of the effects and reducer in there own unit test i think.

**Comment by Steenkuyl** [comment]
So i think you have to create an fake dispatcher and spy on that

**Comment by JimLynchCodes** [comment]
ah I see.

It's a little tricky because you aren't spying on the component you are testing. Instead, you need to spy on the dependency of the component being tested (in this case, spy on the the "dispatch" method of Store that is injected into the component under test).

Hmm, I'll play around with this more and try to do that. :)

**Comment by Steenkuyl** [comment]
I saw a video from Julie Ralph on how the tests should tell the story. But i also see your point, you don't want to test something that already has been tested. So that's my dilemma. I have a component that only dispatches some actions. Or is this more an e2e test than a unit test? What do you think?

**Comment by JimLynchCodes** [comment]
Well Julie Ralph is the mastermind creator of Protractor, the official e2e testing tool for Angular. But since we are taking about karma and jasmine here these are unit tests, not e2e tests. :)

For this example I think using the regular Store would work fine since as far as your test is concerned the dispatched events are basically being ignored. But for the sake of "doing things the right way" I think it would make sense here to spy on the dispatch method.

**Comment by Steenkuyl** [comment]
Your the man :-)

**Comment by JimLynchCodes** [comment]
Hey @Steenkuyl, check this out- I was able to setup a MockStore class and use the "providers" property in the "TestBed.configureTestingModule" to have the MockStore class injected into the component under test instead of the real Store.

```
class MockStore {
  public dispatch(obj) {
    console.log('dispatching from the mock store!')
  }

  public select(obj) {
    console.log('selecting from the mock store!');

    return Observable.of({}})
  }
}


describe('AppComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent,
        SmartComponentComponent,
        DumbComponentComponent,
      ],
      imports: [
        StoreModule.provideStore({mainReducer})
      ],
      providers: [
        {provide: Store, useClass: MockStore}
      ]
    });
  });
```

This should get the job done, but it is pretty annoying having to build up a whole mock class if you just want to override the _dispatch_ method. I'm still looking into how you could spyOn just the dispatch method of store. :)

**Comment by JimLynchCodes** [comment]
Hey @Steenkuyl,

Just wanted to let you know that I figured out how to spyOn just the dispatch method of store! I have two different spec files now for app.component.ts: one that mocks the Store with a defined MockStore class and one that just uses spyOn to override the dispatch method. Check them out!

mocking store: https://github.com/JimTheMan/Jims-Ngrx-Example/blob/master/jims-ngrx-eg/src/app/app.component.with-store-mock.spec.ts

spying on Store method:https://github.com/JimTheMan/Jims-Ngrx-Example/blob/master/jims-ngrx-eg/src/app/app.component.with-store-spy.spec.ts

And that's why they call me JimTheMan. :) 👍

**Comment by JimLynchCodes** [comment]
Just added an example for unit testing reducers as well:
https://github.com/JimTheMan/Jims-Ngrx-Example/blob/master/jims-ngrx-eg/src/app/state-management/reducers/main-reducer.spec.ts

**Comment by JimLynchCodes** [comment]
Ok I'm going to close this issue. Let me know if you have any more questions. :)
